
import express from 'express';
import { getPokemonByNameHandler } from './tools/getPokemonByName';
import { getBerryByNameHandler } from './tools/getBerryByName';
import { getAbilityByNameHandler } from './tools/getAbilityByName';
import { getBerryFirmnessByNameHandler } from './tools/getBerryFirmnessByName';
import { getBerryFlavorByNameHandler } from './tools/getBerryFlavorByName';
import { getCharacteristicByIdHandler } from './tools/getCharacteristicById';
import { getContestEffectByIdHandler } from './tools/getContestEffectById';
import { getContestTypeByNameHandler } from './tools/getContestTypeByName';
import { getEggGroupByNameHandler } from './tools/getEggGroupByName';
import { getEncounterConditionByNameHandler } from './tools/getEncounterConditionByName';
import { getEncounterConditionValueByNameHandler } from './tools/getEncounterConditionValueByName';
import { getEncounterMethodByNameHandler } from './tools/getEncounterMethodByName';
import { getEvolutionChainByIdHandler } from './tools/getEvolutionChainById';
import { getEvolutionTriggerByNameHandler } from './tools/getEvolutionTriggerByName';
import { getGenerationByNameHandler } from './tools/getGenerationByName';
import { getGrowthRateByNameHandler } from './tools/getGrowthRateByName';
import { getItemByNameHandler } from './tools/getItemByName';
import { getItemAttributeByNameHandler } from './tools/getItemAttributeByName';
import { getItemCategoryByNameHandler } from './tools/getItemCategoryByName';
import { getItemFlingEffectByNameHandler } from './tools/getItemFlingEffectByName';
import { getItemPocketByNameHandler } from './tools/getItemPocketByName';
import { getLanguageByNameHandler } from './tools/getLanguageByName';
import { getLocationByNameHandler } from './tools/getLocationByName';
import { getLocationAreaByNameHandler } from './tools/getLocationAreaByName';
import { getMachineByIdHandler } from './tools/getMachineById';
import { getMoveByNameHandler } from './tools/getMoveByName';
import { getMoveAilmentByNameHandler } from './tools/getMoveAilmentByName';
import { getMoveBattleStyleByNameHandler } from './tools/getMoveBattleStyleByName';
import { getMoveCategoryByNameHandler } from './tools/getMoveCategoryByName';
import { getMoveDamageClassByNameHandler } from './tools/getMoveDamageClassByName';
import { getMoveLearnMethodByNameHandler } from './tools/getMoveLearnMethodByName';
import { getMoveTargetByNameHandler } from './tools/getMoveTargetByName';
import { getNatureByNameHandler } from './tools/getNatureByName';
import { getPalParkAreaByNameHandler } from './tools/getPalParkAreaByName';
import { getPokeathlonStatByNameHandler } from './tools/getPokeathlonStatByName';
import { getPokedexByNameHandler } from './tools/getPokedexByName';
import { getPokemonColorByNameHandler } from './tools/getPokemonColorByName';
import { getPokemonFormByNameHandler } from './tools/getPokemonFormByName';
import { getPokemonHabitatByNameHandler } from './tools/getPokemonHabitatByName';
import { getPokemonShapeByNameHandler } from './tools/getPokemonShapeByName';
import { getPokemonSpeciesByNameHandler } from './tools/getPokemonSpeciesByName';
import { getRegionByNameHandler } from './tools/getRegionByName';
import { getStatByNameHandler } from './tools/getStatByName';
import { getSuperContestEffectByIdHandler } from './tools/getSuperContestEffectById';
import { getTypeByNameHandler } from './tools/getTypeByName';
import { getVersionByNameHandler } from './tools/getVersionByName';
import { getVersionGroupByNameHandler } from './tools/getVersionGroupByName';

const router = express.Router();

router.post('/tools/getPokemonByName', getPokemonByNameHandler);
router.post('/tools/getBerryByName', getBerryByNameHandler);
router.post('/tools/getAbilityByName', getAbilityByNameHandler);
router.post('/tools/getBerryFirmnessByName', getBerryFirmnessByNameHandler);
router.post('/tools/getBerryFlavorByName', getBerryFlavorByNameHandler);
router.post('/tools/getCharacteristicById', getCharacteristicByIdHandler);
router.post('/tools/getContestEffectById', getContestEffectByIdHandler);
router.post('/tools/getContestTypeByName', getContestTypeByNameHandler);
router.post('/tools/getEggGroupByName', getEggGroupByNameHandler);
router.post('/tools/getEncounterConditionByName', getEncounterConditionByNameHandler);
router.post('/tools/getEncounterConditionValueByName', getEncounterConditionValueByNameHandler);
router.post('/tools/getEncounterMethodByName', getEncounterMethodByNameHandler);
router.post('/tools/getEvolutionChainById', getEvolutionChainByIdHandler);
router.post('/tools/getEvolutionTriggerByName', getEvolutionTriggerByNameHandler);
router.post('/tools/getGenerationByName', getGenerationByNameHandler);
router.post('/tools/getGrowthRateByName', getGrowthRateByNameHandler);
router.post('/tools/getItemByName', getItemByNameHandler);
router.post('/tools/getItemAttributeByName', getItemAttributeByNameHandler);
router.post('/tools/getItemCategoryByName', getItemCategoryByNameHandler);
router.post('/tools/getItemFlingEffectByName', getItemFlingEffectByNameHandler);
router.post('/tools/getItemPocketByName', getItemPocketByNameHandler);
router.post('/tools/getLanguageByName', getLanguageByNameHandler);
router.post('/tools/getLocationByName', getLocationByNameHandler);
router.post('/tools/getLocationAreaByName', getLocationAreaByNameHandler);
router.post('/tools/getMachineById', getMachineByIdHandler);
router.post('/tools/getMoveByName', getMoveByNameHandler);
router.post('/tools/getMoveAilmentByName', getMoveAilmentByNameHandler);
router.post('/tools/getMoveBattleStyleByName', getMoveBattleStyleByNameHandler);
router.post('/tools/getMoveCategoryByName', getMoveCategoryByNameHandler);
router.post('/tools/getMoveDamageClassByName', getMoveDamageClassByNameHandler);
router.post('/tools/getMoveLearnMethodByName', getMoveLearnMethodByNameHandler);
router.post('/tools/getMoveTargetByName', getMoveTargetByNameHandler);
router.post('/tools/getNatureByName', getNatureByNameHandler);
router.post('/tools/getPalParkAreaByName', getPalParkAreaByNameHandler);
router.post('/tools/getPokeathlonStatByName', getPokeathlonStatByNameHandler);
router.post('/tools/getPokedexByName', getPokedexByNameHandler);
router.post('/tools/getPokemonColorByName', getPokemonColorByNameHandler);
router.post('/tools/getPokemonFormByName', getPokemonFormByNameHandler);
router.post('/tools/getPokemonHabitatByName', getPokemonHabitatByNameHandler);
router.post('/tools/getPokemonShapeByName', getPokemonShapeByNameHandler);
router.post('/tools/getPokemonSpeciesByName', getPokemonSpeciesByNameHandler);
router.post('/tools/getRegionByName', getRegionByNameHandler);
router.post('/tools/getStatByName', getStatByNameHandler);
router.post('/tools/getSuperContestEffectById', getSuperContestEffectByIdHandler);
router.post('/tools/getTypeByName', getTypeByNameHandler);
router.post('/tools/getVersionByName', getVersionByNameHandler);
router.post('/tools/getVersionGroupByName', getVersionGroupByNameHandler);

export default router;
